name: Python Pytest CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 11 for ANTLR4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download and set up ANTLR4 tool
      run: |
        echo "Downloading ANTLR4 complete JAR..."
        wget https://www.antlr.org/download/antlr-4.13.1-complete.jar -O "$GITHUB_WORKSPACE/antlr4-complete.jar"

        echo "Creating 'antlr4' command script..."
        echo 'java -jar "$GITHUB_WORKSPACE/antlr4-complete.jar" "$@"' | sudo tee /usr/local/bin/antlr4
        
        echo "Making 'antlr4' command executable..."
        sudo chmod +x /usr/local/bin/antlr4
        
        echo "Verifying ANTLR4 installation..."
        antlr4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        echo "Upgrading pip..."
        python -m pip install --upgrade pip
        echo "Installing requirements from requirements.txt..."
        pip install -r requirements.txt

    - name: Run Black formatter check
      run: |
        echo "Running Black formatter check..."
        black --check .
      continue-on-error: true

    - name: Run Pytest with Coverage
      run: |
        echo "Running Pytest with coverage..."
        pytest --cov=. --cov-report=xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
